;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-slash
	dired-clean-directory
	indent-for-tab-command
	kill-region
	markdown-cycle
	markdown-outdent-or-delete
	ns-copy-including-secondary
	org-self-insert-command
	yaml-electric-dash-and-dot
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	counsel-M-x
	counsel-find-file
	))
