;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	counsel-M-x
	indent-for-tab-command
	markdown-outdent-or-delete
	ns-copy-including-secondary
	org-self-insert-command
	yaml-electric-dash-and-dot
	))

(setq mc/cmds-to-run-once
      '(
	mark-whole-buffer
	projectile-run-project
	yaml-electric-backspace
	))
