;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	indent-for-tab-command
	kill-region
	markdown-cycle
	markdown-outdent-or-delete
	ns-copy-including-secondary
	org-self-insert-command
	yaml-electric-dash-and-dot
	))

(setq mc/cmds-to-run-once
      '(
	end-of-buffer
	end-of-buffer-other-window
	er/move-line-down
	mark-whole-buffer
	mouse-set-region
	projectile-run-project
	swiper
	yaml-electric-backspace
	))
